FROM node:10.15.0
RUN mkdir /app
WORKDIR /app
COPY ./ir_parking_mobile_app_backend/package.json /app
RUN npm install
COPY ./ir_parking_mobile_app_backend /app
EXPOSE 8080
CMD ["node","ir_parking_db_server.js"]